apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pve-cluster-autoscaler-cr
rules:
- apiGroups: ["", "metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "watch", "list", "patch"]
