apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pve-cluster-autoscaler-rbac
subjects:
- kind: ServiceAccount
  name: pve-cluster-autoscaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pve-cluster-autoscaler-cr
  apiGroup: rbac.authorization.k8s.io
  
