apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - kind: ServiceAccount
    name: demo
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

