apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-cluster-autoscaler
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
        name: pve-cluster-autoscaler
  template:
    metadata:
      labels:
        name: pve-cluster-autoscaler
    spec:
      serviceAccountName: pve-cluster-autoscaler-sa
      containers:
      - name: pve-cluster-autoscaler
        image: namanarora/pve-cluster-autoscaler:latest
        volumeMounts:
          - name: proxmox-secrets
            mountPath: "/etc/secrets"
            readOnly: true
          - name: cloud-init
            mountPath: "/etc/cloud"
            readOnly: true
          - name: ssh-privatekey
            mountPath: "/etc/ssh"
            readOnly: true
        envFrom:
        - configMapRef:
            name: postgres-db-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      initContainers:
      - name: init-postgres
        image: busybox:latest
        command: ['sh', '-c', "until nslookup postgres-db-lb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres-db; sleep 2; done"]
      - name: init-metrics-server
        image: busybox:latest
        command: ['sh', '-c', "until nslookup metrics-server.kube-system.svc.cluster.local; do echo waiting for metrics-server; sleep 2; done"]
      volumes:
      - name: proxmox-secrets
        secret:
          secretName: proxmox-secrets
      - name: cloud-init
        configMap:
          name: cloud-init
      - name: ssh-privatekey
        secret:
          secretName: ssh-privatekey
          defaultMode: 384
