apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-cluster-autoscaler
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
        name: pve-cluster-autoscaler
  template:
    metadata:
      labels:
        name: pve-cluster-autoscaler
    spec:
      serviceAccountName: pve-cluster-autoscaler-sa
      containers:
      - name: pve-cluster-autoscaler
        image: namanarora/pve-cluster-autoscaler:latest
        volumeMounts:
          - name: proxmox-secrets
            mountPath: "/etc/secrets"
            readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: proxmox-secrets
        secret:
          secretName: proxmox-secrets
      - name: cloud-init
        configMap:
          name: cloud-init
