# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
        task: autoscaler
    spec:
      containers:
      - name: postgresql-db
        image: postgres:latest
        volumeMounts:
          - name: postgresql-db-disk
            mountPath: /data
        envFrom:
        - configMapRef:
            name: postgres-db-config
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
